/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package spapi.model.productPricing;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Common properties of batch requests against individual APIs.
 */
@ApiModel(description = "Common properties of batch requests against individual APIs.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-10-13T13:52:33.511+08:00")
public class BatchRequest {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("method")
  private HttpMethod method = null;

  @SerializedName("headers")
  private HttpRequestHeaders headers = null;

  public BatchRequest uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * The &#x60;getItemOffers&#x60; resource path without any query parameters.  **Example:** &#x60;/products/pricing/v0/items/B000P6Q7MY/offers&#x60;
   * @return uri
  **/
  @ApiModelProperty(required = true, value = "The `getItemOffers` resource path without any query parameters.  **Example:** `/products/pricing/v0/items/B000P6Q7MY/offers`")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public BatchRequest method(HttpMethod method) {
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @ApiModelProperty(required = true, value = "")
  public HttpMethod getMethod() {
    return method;
  }

  public void setMethod(HttpMethod method) {
    this.method = method;
  }

  public BatchRequest headers(HttpRequestHeaders headers) {
    this.headers = headers;
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @ApiModelProperty(value = "")
  public HttpRequestHeaders getHeaders() {
    return headers;
  }

  public void setHeaders(HttpRequestHeaders headers) {
    this.headers = headers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchRequest batchRequest = (BatchRequest) o;
    return Objects.equals(this.uri, batchRequest.uri) &&
        Objects.equals(this.method, batchRequest.method) &&
        Objects.equals(this.headers, batchRequest.headers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, method, headers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchRequest {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

